# Generated by Django 3.1.12 on 2025-07-16 06:01

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100000000)),
                ('dec', models.CharField(max_length=100)),
                ('Visibility_status', models.CharField(max_length=100)),
                ('url_key', models.CharField(max_length=100)),
                ('meta_titel', models.CharField(max_length=100)),
                ('meta_keyword', models.CharField(max_length=100)),
                ('meta_dec', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='n_category',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('dec', models.CharField(max_length=100)),
                ('Visibility_status', models.CharField(max_length=100)),
                ('url_key', models.CharField(max_length=100)),
                ('meta_titel', models.CharField(max_length=100)),
                ('meta_keyword', models.CharField(max_length=100)),
                ('meta_dec', models.CharField(max_length=100)),
            ],
        ),
    ]
