# Generated by Django 3.1.12 on 2025-07-16 07:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_d', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('free_delivery', models.CharField(max_length=10)),
                ('visibility', models.CharField(max_length=20)),
                ('url_key', models.CharField(max_length=100)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=160)),
            ],
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
